# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-30 07:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamehub', '0007_auto_20170330_0706'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
    ]
