# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-30 07:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gamehub', '0013_remove_post_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catTitle', models.CharField(db_index=True, max_length=100, null=True)),
                ('slug', models.SlugField(default='Slug', max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default='Slug', max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gamehub.Category'),
        ),
        migrations.DeleteModel(
            name='Category1',
        ),
    ]
